.PHONY: helpers-build helpers-clean

HELPERS_LIBS = $(shell pkg-config --libs xrandr x11)

$(HELPERS)/%: $(HELPERS)/%.c
	gcc -o $@ $< $(HELPERS_LIBS)

bin_HELPERS = $(HELPERS_DIR)/list-outputs \
              $(HELPERS_DIR)/find-free-display \
              $(HELPERS_DIR)/xephyr-window

helpers-build: $(bin_HELPERS)

helpers-clean:
	rm -f $(bin_HELPERS)
