TESTS_TMP=$(TESTS_DIR)/tmp

test-devbot:
	mkdir -p $(TESTS_TMP) && \
	cd tests/devbot && \
	TMPDIR=$(TESTS_TMP) PYTHONPATH=$(BASE_DIR) python -m unittest discover
	rm -rf $(TESTS_TMP)

PYTHON_SCRIPTS = \
    $(COMMANDS_DIR)/build \
    $(COMMANDS_DIR)/clean \
    $(COMMANDS_DIR)/pull \
    $(COMMANDS_DIR)/run-tests \
    $(COMMANDS_DIR)/shell \
    $(COMMANDS_DIR)/check-system \
    $(COMMANDS_DIR)/distribute \
    $(COMMANDS_DIR)/run \
    $(COMMANDS_DIR)/send-patches \
    $(TOOLS_DIR)/json-normalize

pylint:
	PYTHONPATH=$(COMMANDS_DIR) \
	pylint --reports=n --disable=C,W,R,E,F --enable=W0611 \
               devbot $(PYTHON_SCRIPTS)

pep8:
	pep8 commands devbot tests $(PYTHON_SCRIPTS)

check: test-devbot pep8 pylint run-tests
