JSON_FORMAT=$(TOOLS_DIR)/json-format

CONFIG_DEPS_DIR=config/deps

CONFIG_DEPS= \
	$(CONFIG_DEPS_DIR)/prerequisites.json \
	$(CONFIG_DEPS_DIR)/sugar-build.json \
	$(CONFIG_DEPS_DIR)/sugar-buildtime.json \
	$(CONFIG_DEPS_DIR)/sugar-buildtime.json \
	$(CONFIG_DEPS_DIR)/sugar-runtime.json \
	$(CONFIG_DEPS_DIR)/system.json

CONFIG_MODULES_DIR=config/modules

CONFIG_MODULES= \
	$(CONFIG_MODULES_DIR)/activities.json \
	$(CONFIG_MODULES_DIR)/sugar.json \
	$(CONFIG_MODULES_DIR)/system.json

CONFIG_PACKAGES_DIR=config/packages

CONFIG_PACKAGES= \
	$(CONFIG_PACKAGES_DIR)/basesystem.json \
	$(CONFIG_PACKAGES_DIR)/deps.json

CONFIG_MAIN=config/config.json

config-format:
	@$(JSON_FORMAT) $(CONFIG_MODULES) $(CONFIG_PACKAGES) $(CONFIG_MAIN)
	@$(JSON_FORMAT) --sort-by name $(CONFIG_DEPS)
