HELPERS = $(COMMANDS)/helpers

HELPERS_LIBS = $(shell pkg-config --libs xrandr x11)

$(HELPERS)/%: $(HELPERS)/%.c
	gcc -o $@ $< $(HELPERS_LIBS)

bin_HELPERS = $(HELPERS)/list-outputs \
              $(HELPERS)/find-free-display \
              $(HELPERS)/xephyr-window

helpers: $(bin_HELPERS)

clean-helpers:
	rm -f $(bin_HELPERS)
