JSON_NORMALIZE=$(HELPERS_DIR)/json-normalize

CONFIG_DEPS_DIR=config/deps

CONFIG_DEPS= \
	$(CONFIG_DEPS_DIR)/prerequisites.json \
	$(CONFIG_DEPS_DIR)/sugar-build.json \
	$(CONFIG_DEPS_DIR)/sugar-buildtime-3.4.json \
	$(CONFIG_DEPS_DIR)/sugar-buildtime-3.6.json \
	$(CONFIG_DEPS_DIR)/sugar-runtime-3.4.json \
	$(CONFIG_DEPS_DIR)/sugar-runtime-3.6.json \
	$(CONFIG_DEPS_DIR)/system.json

CONFIG_MODULES_DIR=config/modules

CONFIG_MODULES= \
	$(CONFIG_MODULES_DIR)/activities.json \
	$(CONFIG_MODULES_DIR)/sugar.json \
	$(CONFIG_MODULES_DIR)/system-3.4.json \
	$(CONFIG_MODULES_DIR)/system-3.6.json

CONFIG_PACKAGES_DIR=config/packages

OONFIG_PACKAGES= \
	$(CONFIG_PACKAGES_DIR)/basesystem.json \
	$(CONFIG_PACKAGES_DIR)/buildslave.json \
	$(CONFIG_PACKAGES_DIR)/deps-3.4.json \
	$(CONFIG_PACKAGES_DIR)/deps-3.6.json

json-normalize:
	@$(JSON_NORMALIZE) $(CONFIG_MODULES) $(OONFIG_PACKAGES)
	@$(JSON_NORMALIZE) --sort-by name $(CONFIG_DEPS)
