JSON_NORMALIZE=$(TOOLS_DIR)/json-normalize

CONFIG_DEPS_DIR=config/deps

CONFIG_DEPS= \
	$(CONFIG_DEPS_DIR)/prerequisites.json \
	$(CONFIG_DEPS_DIR)/sugar-build.json \
	$(CONFIG_DEPS_DIR)/sugar-buildtime.json \
	$(CONFIG_DEPS_DIR)/sugar-buildtime.json \
	$(CONFIG_DEPS_DIR)/sugar-runtime.json \
	$(CONFIG_DEPS_DIR)/system.json

CONFIG_MODULES_DIR=config/modules

CONFIG_MODULES= \
	$(CONFIG_MODULES_DIR)/activities.json \
	$(CONFIG_MODULES_DIR)/sugar.json \
	$(CONFIG_MODULES_DIR)/system.json

CONFIG_PACKAGES_DIR=config/packages

OONFIG_PACKAGES= \
	$(CONFIG_PACKAGES_DIR)/basesystem.json \
	$(CONFIG_PACKAGES_DIR)/buildslave.json \
	$(CONFIG_PACKAGES_DIR)/deps.json

config-normalize:
	@$(JSON_NORMALIZE) $(CONFIG_MODULES) $(OONFIG_PACKAGES)
	@$(JSON_NORMALIZE) --sort-by name $(CONFIG_DEPS)
