.PHONY: auto-install check-system build run test shell bug-report clean

auto-install:
	@$(COMMANDS_DIR)/auto-install

check-system:
	@$(COMMANDS_DIR)/check-system $(ARGS)

pull:
	@$(COMMANDS_DIR)/pull

build:
	@$(COMMANDS_DIR)/build

run:
	@$(COMMANDS_DIR)/run

test-ui:
	@$(COMMANDS_DIR)/test-ui

shell:
	@$(COMMANDS_DIR)/shell

bug-report:
	@$(COMMANDS_DIR)/bug-report

clean:
	@$(COMMANDS_DIR)/clean

build-%:
	@$(COMMANDS_DIR)/build $*

pull-%:
	@$(COMMANDS_DIR)/pull $*
