#!/bin/sh

scriptsdir=`dirname "$0"`
rootdir=`dirname "$scriptsdir"`
buildlogsdir=$rootdir/logs
sugarlogsdir=~/.sugar/default/logs
tarfile=$buildlogsdir/all-logs.tar.bz2

tarcommand="tar cfj $tarfile"

if [ -d $buildlogsdir ]; then
    buildlogs=`cd $buildlogsdir; find *.log`
    tarcommand="$tarcommand -C $buildlogsdir $buildlogs"
fi

if [ -d $sugarlogsdir ]; then
    sugarlogs=`cd $sugarlogsdir; find *.log`
    tarcommand="$tarcommand -C $sugarlogsdir $sugarlogs"
fi

$tarcommand

echo
echo "Send an email to Daniel Narvaez <dwnarvaez@gmail.com>."
echo "Attach the $tarfile file."
echo
