#!/usr/bin/python -u

import argparse
import sys

import common

from devbot import build

parser = argparse.ArgumentParser()
parser.add_argument("module", nargs="?", help="name of the module to build")
args = parser.parse_args()

common.setup()

if args.module:
    success = build.build_one(args.module)
else:
    success = build.build()

if not success:
    sys.exit(1)
