#!/usr/bin/python -u

import argparse
import sys

import common

from devbot import system
from devbot import build

parser = argparse.ArgumentParser()
parser.add_argument("module", nargs="?", help="name of the module to build")
parser.add_argument("--full", action="store_true", help="force a full build")
args = parser.parse_args()

common.setup(log_name="build")

if not system.check(skip_if_unchanged=True):
    sys.exit(1)

if args.module:
    success = build.build_one(args.module)
else:
    success = build.build(full=args.full)

if not success:
    sys.exit(1)
