#!/usr/bin/env python

import argparse
import sys

import common

from osbuild import build
from osbuild import main


parser = argparse.ArgumentParser()
parser.add_argument("module", nargs="?", help="name of the module to build")
parser.add_argument("--full", action="store_true", help="force a full build")
args = parser.parse_args()

common.setup(log_name="build")

if args.module:
    if not build.build_one(args.module):
        sys.exit(1)
else:
    if not main.run_build(full=args.full):
        sys.exit(1)
