#!/usr/bin/python

import argparse

import common

from devbot import system
from devbot import config
from devbot import distro

common.setup()

parser = argparse.ArgumentParser(description='Check the system')
parser.add_argument("--update", action="store_true",
                    help="first of all update the system")
parser.add_argument("--remove", action="store_true",
                    help="remove all the unnecessary packages")
parser.add_argument("--test", action="store_true",
                    help="don't add or remove packages, test only")
args = parser.parse_args()

def apply_ubuntu_tweaks():
    wrapper_config = open("/etc/X11/Xwrapper.config").read()
    if "allowed_users=anybody" not in wrapper_config:
        print "\nWe are going to allow anybody to run the X server"

        ubuntu_tweaks = os.path.join(config.commands_dir,
                                     "helpers", "ubuntu-tweaks")

        command.run_with_sudo([ubuntu_tweaks])

if distro.get_distro_name() == "ubuntu":
    apply_ubuntu_tweaks()

system.check(update=args.update, remove=args.remove, test=args.test)
