#!/usr/bin/python -u

import argparse
import os

import common

from devbot import system

common.setup()

parser = argparse.ArgumentParser(description='Check the system')
parser.add_argument("--update", action="store_true",
                    help="first of all update the system")
parser.add_argument("--remove", action="store_true",
                    help="remove all the unnecessary packages")
parser.add_argument("--test", action="store_true",
                    help="don't add or remove packages, test only")
args = parser.parse_args()

interactive = "SUGAR_BUILDBOT" not in os.environ

system.check(update=args.update,
             remove=args.remove,
             test=args.test,
             interactive=interactive)
