#!/usr/bin/env python

import argparse
import sys
import json

import common

from devbot import build
from devbot import command

parser = argparse.ArgumentParser()
parser.add_argument("module", nargs="?", help="name of the module to pull")
parser.add_argument("--revisions", help="json dict with the revisions to pull")
args = parser.parse_args()

common.setup(log_name="pull")

if args.module:
    if not build.pull_one(args.module):
        sys.exit(1)
else:
    revisions = {}
    if args.revisions:
        revisions = json.loads(args.revisions)

    if not build.pull(revisions):
        sys.exit(1)

    if not common.is_buildbot():
        print("* Pulling sugar-build")
        command.run(["git", "pull", "--ff-only"])
