#!/usr/bin/python -u

import argparse
import sys

import common

from devbot import build

parser = argparse.ArgumentParser()
parser.add_argument("module", nargs="?", help="name of the module to pull")
args = parser.parse_args()

common.setup(log_name="pull")

if args.module:
    if not build.pull_one(args.module):
        sys.exit(1)
else:
    if not build.pull():
        sys.exit(1)
