#!/bin/bash

commandsdir=`dirname "$0"`
helpersdir=$commandsdir/helpers
rootdir=`dirname "$commandsdir"`
display=`$helpersdir/find-free-display`

if [ -f $rootdir/prefs ]; then
    source $rootdir/prefs
fi

if [ -n $SUGAR_DISPLAY ]; then
    SUGAR_XKBCONFIG=`mktemp -t sugar-xkbconfig-XXXXXX`
    setxkbmap -print > $SUGAR_XKBCONFIG
    export SUGAR_XKBCONFIG
fi

if [ ! -z $SUGAR_PROFILE ]; then
    grep -q PROFILE $rootdir/prefs
    if [ $? -eq 1 ]; then
        randomstring=`</dev/urandom tr -cd A-Za-z0-9 | head -c10`
        echo "PROFILE=$randomstring" >> $ROOT_DIR/prefs
    fi
fi

if [ -z $DISPLAY ]; then
    tty_num=`tty | grep -oE '[0-9]+$'`
    x_options="vt$tty_num"

    xinit $helpersdir/xinitrc -- $display $x_options
else
    screen_dpi=`$helpersdir/get-screen-dpi`
    xephyr_options="-dpi $screen_dpi"

    if [ -z $RUN_IN_WINDOW ]; then
        xephyr_options="$xephyr_options -fullscreen"
    fi

    if [ ! -z $RESOLUTION ]; then
        xephyr_options="$xephyr_options -screen $RESOLUTION"
    fi

    xinit $helpersdir/xinitrc -- /usr/bin/Xephyr $display $xephyr_options
fi
