#!/usr/bin/python

import sys

import common

from devbot import run
from devbot import build
from devbot import system

common.setup(log_name="run")

if not system.check(lazy=True):
    sys.exit(1)

if not build.pull(lazy=True):
    sys.exit(1)

if not build.build():
    sys.exit(1)

run.run("sugar-runner")
