#!/usr/bin/python

import os

import common

from devbot import shell
from devbot import environ

common.setup()

commands_dir = os.path.join(common.base_dir, "commands")

environ.add_path("PATH", commands_dir)
shell.start(os.path.join(commands_dir, "bashrc"))
