#!/bin/sh

commandsdir=`dirname "$0"`
destdir=`dirname "$commandsdir"`
filename=snapshot.tar
rootdir=sugar-snapshot

mkdir -p $destdir
ln -s `pwd` $destdir/$rootdir

cd $destdir

tar cvhf $filename \
    $rootdir/config \
    $rootdir/devbot \
    $rootdir/install \
    $rootdir/commands/check-system \
    $rootdir/commands/common.py \
    $rootdir/commands/bashrc \
    $rootdir/commands/run \
    $rootdir/commands/shell

rm $rootdir
mkdir $rootdir

runsugarscript=$rootdir/run-sugar.sh

cat > $runsugarscript << "EOF"
#!/bin/sh

commands/run
EOF

chmod +x $runsugarscript

runshellscript=$rootdir/run-shell.sh

cat > $runshellscript << "EOF"
#!/bin/sh

commands/shell
EOF

chmod +x $runshellscript

tar rvh -f $filename $runshellscript $runsugarscript

rm -rf $rootdir

rm -f $filename.xz
xz --verbose $filename
