#!/usr/bin/python

import os

import common

from devbot import run
from devbot import config

common.setup()

run.run([os.path.join(common.helpers_dir, "test"),
         os.path.join(common.base_dir, "tests", "shell.py")])
