#!/usr/bin/python

import os
import sys

import common

from devbot import run

common.setup()

virtual = "SUGAR_BUILDBOT" in os.environ
test_path = os.path.join(common.tests_dir, "sugar", "shell.py")
if not run.run_test(test_path, virtual):
    sys.exit(1)
