#!/bin/bash

shelldir=`dirname "$0"`
scriptsdir=`dirname "$shelldir"`
rootdir=`dirname "$scriptsdir"`
display=`$scriptsdir/find-free-display`
screen_dpi=`$scriptsdir/get-screen-dpi`
xephyr_options="-dpi $screen_dpi"

if [ -f $rootdir/config ]; then
    source $rootdir/config
fi

if [ -n $SUGAR_DISPLAY ]; then
    SUGAR_XKBCONFIG=`mktemp -t sugar-xkbconfig-XXXXXX`
    setxkbmap -print > $SUGAR_XKBCONFIG
    export SUGAR_XKBCONFIG
fi

if [ ! -z $SUGAR_PROFILE ]; then
    grep -q PROFILE $rootdir/config
    if [ $? -eq 1 ]; then
        randomstring=`</dev/urandom tr -cd A-Za-z0-9 | head -c10`
        echo "PROFILE=$randomstring" >> $ROOT_DIR/config
    fi
fi

if [ -z $DISPLAY ]; then
    xinit $scriptsdir/xinitrc -- $display
else
    if [ -z $RUN_IN_WINDOW ]; then
        xephyr_options="$xephyr_options -fullscreen"
    fi

    xinit $scriptsdir/xinitrc -- /usr/bin/Xephyr $display $xephyr_options
fi
