#!/bin/sh

shelldir=`dirname "$0"`
scriptsdir=`dirname "$shelldir"`
rootdir=`dirname "$scriptsdir"`
display=`$scriptsdir/find-free-display`

if [ -f $rootdir/config ]; then
  source $rootdir/config
fi

if [ ! -z $SUGAR_PROFILE ]; then
    grep -q PROFILE $ROOT_DIR/config
    if [ $? -eq 1 ]; then
        randomstring=`</dev/urandom tr -cd A-Za-z0-9 | head -c10`
        echo "PROFILE=$randomstring" >> $ROOT_DIR/config
    fi
fi

if [ -z $RUN_IN_WINDOW ]; then
    xinit $scriptsdir/xinitrc -- $display
else
    xinit $scriptsdir/xinitrc -- /usr/bin/Xvnc $xvncdisplay -SecurityTypes None &
    xvncpid=$!

    xport=`echo $display | cut -c2-`
    xvncport=$(($xport + 5800))
    vncviewer localhost:$xvncport

    kill $xvncpid
fi
