#!/bin/sh

eval `gnome-keyring-daemon --start --components=secrets,pkcs11,ssh,gpg`

export SSH_AUTH_SOCK
export GNOME_KEYRING_CONTROL
export GPG_AGENT_INFO
export GNOME_KEYRING_PID

exec $1

kill $GNOME_KEYRING_PID
