#!/bin/sh

scriptsdir=`dirname "$0"`
rootdir=`dirname "$scriptsdir"`
testsdir=$rootdir/tests
scriptsdir=$rootdir/scripts
logsdir=$rootdir/logs
display=`$scriptsdir/find-free-display`
resolution=1024x768x16

minver="0.8.0"
version=`python -c "import dogtail; print dogtail.__version__"`
if [ "$minver" != "`echo -e "$minver\n$version" | sort -V | head -n1`" ]; then
    echo "Dogtail >= 0.8.0 is required."
    exit 0
fi

xvfb=`which Xvfb`
xserver="$xvfb $display -ac -noreset -shmem -screen 0 $resolution"

if [ -z "$SUGAR_BUILDBOT" ]; then
    xserver=$display
fi

export SUGAR_LOGGER_LEVEL=debug
export GTK_MODULES=gail:atk-bridge
export SUGAR_PROFILE=dogtail

PROFILE_PATH=~/.sugar/dogtail

rm -rf $PROFILE_PATH

xinit $scriptsdir/xinitrc -- $xserver &
xinitpid=$!

sleep 10

DISPLAY=$display python $testsdir/shell.py
result=$?

kill $xinitpid

if [ -z "$SUGAR_BUILDBOT" ]; then
    LOGFILE=$logsdir/test-`date +%Y%m%d-%H%M%S`.tar
else
    LOGFILE=$logsdir/test.tar
fi

cd $PROFILE_PATH/logs
tar cvf $LOGFILE *.log

exit $result
