#!/bin/sh

scriptsdir=`dirname "$0"`
rootdir=`dirname "$scriptsdir"`
testsdir=$rootdir/tests
display=:99
resolution=1024x768x16

minver="0.8.0"
version=`python -c "import dogtail; print dogtail.__version__"`
if [ "$minver" != "`echo -e "$minver\n$version" | sort -V | head -n1`" ]; then
    echo "Dogtail >= 0.8.0 is required."
    exit 0
fi

xvfb=`which Xvfb`
xserver="$xvfb $display -ac -noreset -shmem -screen 0 $resolution"

if [ -z "$SUGAR_BUILDBOT" ]; then
    xserver=$display
fi

export SUGAR_LOGGER_LEVEL=debug
export GTK_MODULES=gail:atk-bridge
export SUGAR_PROFILE=dogtail

rm -rf ~/.sugar/dogtail

xinit $scriptsdir/xinitrc -- $xserver &
xinitpid=$!

# FIXME starting the tests immediately puts dogtail in a broken state
sleep 5

DISPLAY=$display python $testsdir/shell.py
result=$?

kill $xinitpid

exit $result
