#!/bin/sh

scriptsdir=`dirname "$0"`
rootdir=`dirname "$scriptsdir"`
testsdir=$rootdir/tests
scriptsdir=$rootdir/scripts
logsdir=$rootdir/logs
display=`$scriptsdir/find-free-display`
resolution=1024x768x16

minver="0.8.0"
version=`python -c "import dogtail; print dogtail.__version__"`
if [ "$minver" != "`echo -e "$minver\n$version" | sort -V | head -n1`" ]; then
    echo "Dogtail >= 0.8.0 is required."
    exit 0
fi

xvfb=`which Xvfb`
xserver="$xvfb $display -ac -noreset -shmem -screen 0 $resolution"

if [ -z "$SUGAR_BUILDBOT" ]; then
    xserver=$display
fi

export SUGAR_LOGGER_LEVEL=debug
export GTK_MODULES=gail:atk-bridge
export SUGAR_DOGTAIL=yes

xinit $scriptsdir/xinitrc -- $xserver &
xinitpid=$!

sleep 20

DISPLAY=$display python $testsdir/shell.py
result=$?

kill $xinitpid

if [ -z "$SUGAR_BUILDBOT" ]; then
    LOGFILE=$logsdir/test-`date +%Y%m%d-%H%M%S`.log
else
    LOGFILE=$logsdir/test.log
fi

cd ~/.sugar/dogtail/logs

for logfile in *.log
do
 echo -e "===== $logfile =====\n" >> $LOGFILE
 cat $logfile >> $LOGFILE
 echo >> $LOGFILE
done

exit $result
