unset GPG_AGENT_INFO
unset SSH_AUTH_SOCK
unset GNOME_KEYRING_CONTROL
unset GNOME_KEYRING_PID
unset SESSION_MANAGER

SCRIPTS_DIR=`dirname "$0"`
ROOT_DIR=`dirname "$SCRIPTS_DIR"`

if [ ! -z $SUGAR_PROFILE ]; then
    grep -q PROFILE $ROOT_DIR/config
    if [ $? -ne 0 ]; then
        randomstring=`</dev/urandom tr -cd A-Za-z0-9 | head -c10`
        echo "PROFILE=$randomstring" >> $ROOT_DIR/config
    fi
fi

if [ -f $ROOT_DIR/config ]; then
    source $ROOT_DIR/config
fi

# Sugar doesn't handle multiple outputs properly. To avoid issues we keep the
# first output in the list returned by xrandr and turn off everything else.

OUTPUTS=`$SCRIPTS_DIR/list-outputs`

for output in $OUTPUTS
do
   # Default to the first output in the list
   if [ -z $OUTPUT ]; then
       OUTPUT=$output
   fi

   if [ $OUTPUT != $output ]; then
       xrandr --output $output --off
   fi
done

if [ ! -z $RESOLUTION ]; then
    xrandr -s $RESOLUTION
fi

if [ ! -z $SUGAR_UI_TESTS ]; then
    rm -rf ~/.sugar/ui-tests
    export SUGAR_PROFILE=ui-tests
elif [ ! -z $PROFILE ]; then
    export SUGAR_PROFILE=$PROFILE
fi

if [ ! -z $SUGAR_XKBCONFIG ]; then
    cat $SUGAR_XKBCONFIG | xkbcomp - $DISPLAY 2> /dev/null
    rm $SUGAR_XKBCONFIG
fi

RUN_COMMAND="dbus-launch --exit-with-session $SCRIPTS_DIR/run-with-keyring sugar"

if [ -z $SUGAR_BUILD_SHELL ]; then
    $SCRIPTS_DIR/dn-build run $RUN_COMMAND
else
    $RUN_COMMAND
fi
