unset GPG_AGENT_INFO
unset SSH_AUTH_SOCK
unset GNOME_KEYRING_CONTROL
unset GNOME_KEYRING_PID

SCRIPTS_DIR=`dirname "$0"`
ROOT_DIR=`dirname "$SCRIPTS_DIR"`

# Sugar doesn't handle multiple outputs properly. To avoid issues we keep the
# first output in the list returned by xrandr and turn off everything else.

OUTPUTS=`scripts/list-outputs`

for output in $OUTPUTS
do
   # Default to the first output in the list
   if [ -z $SUGAR_OUTPUT ]; then
       SUGAR_OUTPUT=$output
   fi

   if [ $SUGAR_OUTPUT != $output ]; then
       xrandr --output $output --off
   fi
done

if [ -z $SUGAR_SESSION ]; then
    export SUGAR_SESSION=yes
else
    export SUGAR_PROFILE=development
fi

JHBUILD="$ROOT_DIR/install/bin/jhbuild -f $ROOT_DIR/scripts/jhbuildrc"
RUN_COMMAND="dbus-launch --exit-with-session sugar"

if [ -z $SUGAR_BUILD_SHELL ]; then
    $JHBUILD run $RUN_COMMAND
else
    $RUN_COMMAND
fi
