unset GPG_AGENT_INFO
unset SSH_AUTH_SOCK
unset GNOME_KEYRING_CONTROL
unset GNOME_KEYRING_PID
unset SESSION_MANAGER

SCRIPTS_DIR=`dirname "$0"`
ROOT_DIR=`dirname "$SCRIPTS_DIR"`

if [ ! -f $ROOT_DIR/config ]; then
    touch $ROOT_DIR/config
fi

if [ ! -z $SUGAR_PROFILE ]; then
    grep -q PROFILE $ROOT_DIR/config
    if [ $? -eq 1 ]; then
        randomstring=`</dev/urandom tr -cd A-Za-z0-9 | head -c10`
        echo "PROFILE=$randomstring" >> $ROOT_DIR/config
    fi
fi

source $ROOT_DIR/config

# Sugar doesn't handle multiple outputs properly. To avoid issues we keep the
# first output in the list returned by xrandr and turn off everything else.

OUTPUTS=`scripts/list-outputs`

for output in $OUTPUTS
do
   # Default to the first output in the list
   if [ -z $OUTPUT ]; then
       OUTPUT=$output
   fi

   if [ $OUTPUT != $output ]; then
       xrandr --output $output --off
   fi
done

if [ ! -z $PROFILE ]; then
    export SUGAR_PROFILE=$PROFILE
fi

eval `ssh-agent -s`

JHBUILD="$ROOT_DIR/install/bin/jhbuild -f $ROOT_DIR/scripts/jhbuildrc"
RUN_COMMAND="dbus-launch --exit-with-session sugar"

if [ -z $SUGAR_BUILD_SHELL ]; then
    $JHBUILD run $RUN_COMMAND
else
    $RUN_COMMAND
fi

kill $SSH_AGENT_PID
